// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/avp/avp.proto

package avp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartProcessRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartProcessRequest) Reset()         { *m = StartProcessRequest{} }
func (m *StartProcessRequest) String() string { return proto.CompactTextString(m) }
func (*StartProcessRequest) ProtoMessage()    {}
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4984b486b530d49c, []int{0}
}

func (m *StartProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartProcessRequest.Unmarshal(m, b)
}
func (m *StartProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartProcessRequest.Marshal(b, m, deterministic)
}
func (m *StartProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartProcessRequest.Merge(m, src)
}
func (m *StartProcessRequest) XXX_Size() int {
	return xxx_messageInfo_StartProcessRequest.Size(m)
}
func (m *StartProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartProcessRequest proto.InternalMessageInfo

type StartProcessReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartProcessReply) Reset()         { *m = StartProcessReply{} }
func (m *StartProcessReply) String() string { return proto.CompactTextString(m) }
func (*StartProcessReply) ProtoMessage()    {}
func (*StartProcessReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4984b486b530d49c, []int{1}
}

func (m *StartProcessReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartProcessReply.Unmarshal(m, b)
}
func (m *StartProcessReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartProcessReply.Marshal(b, m, deterministic)
}
func (m *StartProcessReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartProcessReply.Merge(m, src)
}
func (m *StartProcessReply) XXX_Size() int {
	return xxx_messageInfo_StartProcessReply.Size(m)
}
func (m *StartProcessReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartProcessReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartProcessReply proto.InternalMessageInfo

type StopProcessRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopProcessRequest) Reset()         { *m = StopProcessRequest{} }
func (m *StopProcessRequest) String() string { return proto.CompactTextString(m) }
func (*StopProcessRequest) ProtoMessage()    {}
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4984b486b530d49c, []int{2}
}

func (m *StopProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopProcessRequest.Unmarshal(m, b)
}
func (m *StopProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopProcessRequest.Marshal(b, m, deterministic)
}
func (m *StopProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopProcessRequest.Merge(m, src)
}
func (m *StopProcessRequest) XXX_Size() int {
	return xxx_messageInfo_StopProcessRequest.Size(m)
}
func (m *StopProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopProcessRequest proto.InternalMessageInfo

type StopProcessReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopProcessReply) Reset()         { *m = StopProcessReply{} }
func (m *StopProcessReply) String() string { return proto.CompactTextString(m) }
func (*StopProcessReply) ProtoMessage()    {}
func (*StopProcessReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4984b486b530d49c, []int{3}
}

func (m *StopProcessReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopProcessReply.Unmarshal(m, b)
}
func (m *StopProcessReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopProcessReply.Marshal(b, m, deterministic)
}
func (m *StopProcessReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopProcessReply.Merge(m, src)
}
func (m *StopProcessReply) XXX_Size() int {
	return xxx_messageInfo_StopProcessReply.Size(m)
}
func (m *StopProcessReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopProcessReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopProcessReply proto.InternalMessageInfo

// Element describes an a/v process
type Element struct {
	Mid                  string   `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Rid                  string   `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config               []byte   `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Element) Reset()         { *m = Element{} }
func (m *Element) String() string { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()    {}
func (*Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_4984b486b530d49c, []int{4}
}

func (m *Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Element.Unmarshal(m, b)
}
func (m *Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Element.Marshal(b, m, deterministic)
}
func (m *Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Element.Merge(m, src)
}
func (m *Element) XXX_Size() int {
	return xxx_messageInfo_Element.Size(m)
}
func (m *Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Element proto.InternalMessageInfo

func (m *Element) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *Element) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *Element) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Element) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*StartProcessRequest)(nil), "avp.StartProcessRequest")
	proto.RegisterType((*StartProcessReply)(nil), "avp.StartProcessReply")
	proto.RegisterType((*StopProcessRequest)(nil), "avp.StopProcessRequest")
	proto.RegisterType((*StopProcessReply)(nil), "avp.StopProcessReply")
	proto.RegisterType((*Element)(nil), "avp.Element")
}

func init() { proto.RegisterFile("pkg/proto/avp/avp.proto", fileDescriptor_4984b486b530d49c) }

var fileDescriptor_4984b486b530d49c = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xc8, 0x4e, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0x2b, 0x00, 0x61, 0x3d, 0x30, 0x4f, 0x88, 0x39,
	0xb1, 0xac, 0x40, 0x49, 0x94, 0x4b, 0x38, 0xb8, 0x24, 0xb1, 0xa8, 0x24, 0xa0, 0x28, 0x3f, 0x39,
	0xb5, 0xb8, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x49, 0x98, 0x4b, 0x10, 0x55, 0xb8,
	0x20, 0xa7, 0x52, 0x49, 0x84, 0x4b, 0x28, 0xb8, 0x24, 0xbf, 0x00, 0x4d, 0xa9, 0x10, 0x97, 0x00,
	0x8a, 0x28, 0x48, 0x65, 0x24, 0x17, 0xbb, 0x6b, 0x4e, 0x6a, 0x6e, 0x6a, 0x5e, 0x89, 0x90, 0x00,
	0x17, 0x73, 0x6e, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x09, 0x12, 0x29,
	0xca, 0x4c, 0x91, 0x60, 0x82, 0x88, 0x14, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x54, 0x16,
	0xa4, 0x4a, 0x30, 0x83, 0x85, 0xc0, 0x6c, 0x21, 0x31, 0x2e, 0xb6, 0xe4, 0xfc, 0xbc, 0xb4, 0xcc,
	0x74, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x28, 0xcf, 0xa8, 0x8b, 0x91, 0x8b, 0xd9, 0x31,
	0x2c, 0x40, 0xc8, 0x89, 0x8b, 0x07, 0xd9, 0x85, 0x42, 0x12, 0x7a, 0x20, 0x9f, 0x61, 0xf1, 0x8b,
	0x94, 0x18, 0x16, 0x19, 0x90, 0x23, 0x19, 0x84, 0xec, 0xb9, 0xb8, 0x91, 0x9c, 0x2e, 0x24, 0x0e,
	0x55, 0x88, 0xee, 0x45, 0x29, 0x51, 0x4c, 0x09, 0xb0, 0x01, 0x4e, 0xea, 0x51, 0xaa, 0xe9, 0x99,
	0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x05, 0x99, 0xf9, 0x79, 0xfa, 0x99, 0xf9,
	0x79, 0xba, 0xa0, 0x70, 0x46, 0x09, 0xf5, 0x24, 0x36, 0x30, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xff, 0xd1, 0xc8, 0x94, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AVPClient is the client API for AVP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AVPClient interface {
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessReply, error)
	StopProcess(ctx context.Context, in *StopProcessRequest, opts ...grpc.CallOption) (*StopProcessReply, error)
}

type aVPClient struct {
	cc *grpc.ClientConn
}

func NewAVPClient(cc *grpc.ClientConn) AVPClient {
	return &aVPClient{cc}
}

func (c *aVPClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessReply, error) {
	out := new(StartProcessReply)
	err := c.cc.Invoke(ctx, "/avp.AVP/StartProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aVPClient) StopProcess(ctx context.Context, in *StopProcessRequest, opts ...grpc.CallOption) (*StopProcessReply, error) {
	out := new(StopProcessReply)
	err := c.cc.Invoke(ctx, "/avp.AVP/StopProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AVPServer is the server API for AVP service.
type AVPServer interface {
	StartProcess(context.Context, *StartProcessRequest) (*StartProcessReply, error)
	StopProcess(context.Context, *StopProcessRequest) (*StopProcessReply, error)
}

// UnimplementedAVPServer can be embedded to have forward compatible implementations.
type UnimplementedAVPServer struct {
}

func (*UnimplementedAVPServer) StartProcess(ctx context.Context, req *StartProcessRequest) (*StartProcessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcess not implemented")
}
func (*UnimplementedAVPServer) StopProcess(ctx context.Context, req *StopProcessRequest) (*StopProcessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProcess not implemented")
}

func RegisterAVPServer(s *grpc.Server, srv AVPServer) {
	s.RegisterService(&_AVP_serviceDesc, srv)
}

func _AVP_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVPServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avp.AVP/StartProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVPServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AVP_StopProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AVPServer).StopProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avp.AVP/StopProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AVPServer).StopProcess(ctx, req.(*StopProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AVP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "avp.AVP",
	HandlerType: (*AVPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcess",
			Handler:    _AVP_StartProcess_Handler,
		},
		{
			MethodName: "StopProcess",
			Handler:    _AVP_StopProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/avp/avp.proto",
}
