[pipeline.samplebuilder]
# max late for audio rtp packets
audiomaxlate = 100
# max late for video rtp packets
videomaxlate = 200

[pipeline.webmsaver]
# webm output path
path = "./out/"

[log]
level = "info"
