name: grpc docker
on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build --tag pionwebrtc/ion-avp:latest-grpc -f cmd/server/grpc/Dockerfile .

      - name: login
        if: github.event_name == 'release'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: tag
        if: github.event_name == 'release'
        run: docker tag pionwebrtc/ion-avp:latest-grpc pionwebrtc/ion-avp:"${{ github.event.release.tag_name }}"-grpc

      - name: push
        if: github.event_name == 'release'
        run: docker push pionwebrtc/ion-avp:"${{ github.event.release.tag_name }}"-grpc
