name: grpc docker
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
    
      - name: build
        run: docker build --tag pionwebrtc/ion-avp:latest-grpc -f cmd/server/grpc/Dockerfile .

      - name: login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: tag
        run: docker tag pionwebrtc/ion-avp:latest-grpc pionwebrtc/ion-avp:"${{ github.event.release.tag_name }}"-grpc

      - name: push
        run: docker push pionwebrtc/ion-avp:"${{ github.event.release.tag_name }}"-grpc
